name: SkyblockLevels
version: '${version}'
main: io.github.fisher2911.skyblocklevels.SkyblockLevels
api-version: 1.18
load: STARTUP
depend: [ Lands, packetevents ]
permissions:
  skyblocklevels.giveitem:
    description: "Allows you to give a Skyblock item to a player"
    default: false
  skyblocklevels.randomtp:
    description: "Allows you to teleport to a random area"
    default: true
  skyblocklevels.viewcollection:
    description: "Allows you to view your collection"
    default: true
  skyblocklevels.reload:
    description: "Allows you to reload the plugin"
    default: false