name: SkyblockLevels
version: '${version}'
main: io.github.fisher2911.skyblocklevels.SkyblockLevels
api-version: 1.18
load: POSTWORLD
depend: [ Lands, PlaceholderAPI, LuckPerms ]
permissions:
  skyblocklevels.giveitem:
    description: "Allows you to give a Skyblock item to a player"
    default: op
  skyblocklevels.randomtp:
    description: "Allows you to teleport to a random area"
    default: true
  skyblocklevels.viewcollection:
    description: "Allows you to view your collection"
    default: true
    skyblocklevels.setcollection:
      description: "Allows you to set players collection"
      default: true
  skyblocklevels.reload:
    description: "Allows you to reload the plugin"
    default: op
  skyblocklevels.givebooster:
    description: "Allows you to give a Skyblock booster to a player"
    default: op